import Head from 'next/head'
import HomeSection from '@/components/home/homeSection'
import Header from '@/components/home/header'
import AboutUs from '@/components/about/about'
import Services from '@/components/services/services'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"/>

      </Head>
      
      
      <main className='main'>
        
        <HomeSection />
        <AboutUs/>
        <Services/>
       
      </main>
    </>
  )
}
